//! `string_type_custom("crate::types::FlexStr")`

/// A `ProtoString` backed by [`flexstr::SharedStr`]: short strings inline
/// (no heap), long strings shared via `Arc<str>` so clones are `O(1)`.
///
/// The `buffa::ProtoString` impl, `Deref`/`AsRef`, and the `From`
/// conversions are generated by [`buffa_remote_derive::ProtoString`] — see
/// that crate for the full pattern this collapses (compare to
/// `small_bytes.rs`/`small_vec.rs` in this module, which still hand-write the
/// equivalent boilerplate for traits the derive crate doesn't yet cover).
#[derive(
    Clone,
    PartialEq,
    Eq,
    Hash,
    Default,
    Debug,
    serde::Serialize,
    serde::Deserialize,
    buffa_remote_derive::ProtoString,
)]
#[serde(transparent)]
#[buffa(remote = flexstr::SharedStr)]
#[repr(transparent)]
pub struct FlexStr(pub flexstr::SharedStr);
super::assert_transparent!(FlexStr, flexstr::SharedStr);
