//! `string_type_custom("crate::types::FlexStr")`

/// A `ProtoString` backed by [`flexstr::SharedStr`]: short strings inline
/// (no heap), long strings shared via `Arc<str>` so clones are `O(1)`.
///
/// The `buffa::ProtoString` impl, `Deref`/`AsRef`, and the `From`
/// conversions are generated by [`buffa_remote_derive::ProtoString`] — see
/// that crate for the full pattern this collapses. This type needs its own
/// `Serialize`/`Deserialize`: a singular `string` with implicit presence
/// uses buffa's with-module, and a `repeated` element, a field with explicit
/// presence, a oneof variant, and a map key or value serialize through the
/// type's own serde (see this example's README for the per-newtype JSON
/// table). The derive's
/// `serde` key generates those impls, so `flexstr` is built without its
/// `serde` feature. The other newtypes in this
/// module remain hand-written and show the written-out shape of the
/// pattern; `small_bytes.rs`/`small_vec.rs` stay that way on purpose,
/// because their impls carry allocation behavior the generic derive can't
/// express (`SmallBytes::from_wire` builds straight from the wire slice
/// with no intermediate `Vec`, and `SmallVec`'s `clear` retains capacity
/// where the derive's drops it).
#[derive(Clone, PartialEq, Eq, Hash, Default, Debug, buffa_remote_derive::ProtoString)]
#[buffa(remote = flexstr::SharedStr, serde)]
#[repr(transparent)]
pub struct FlexStr(pub flexstr::SharedStr);
super::assert_transparent!(FlexStr, flexstr::SharedStr);
